#!/bin/bash

kafka-avro-console-producer  \
  --broker-list localhost:9092 \
  --topic phone_event_raw \
  --property value.schema='
{
  "type": "record",
  "name": "myrecord",
  "fields": [
     {"name": "customer_name",  "type": "string" }
   , {"name": "phone_model", "type": "string" }
   , {"name": "event", "type": "string" }
   , {"name": "post_code", "type": "string" }
  ]
}'

